POST /payroll/$batch HTTP/1.1
Host: localhost:4004
Content-Type: multipart/mixed; boundary=batch_123
Content-Length: 458

--batch_123
Content-Type: multipart/mixed; boundary=changeset_123
Content-Transfer-Encoding:binary

--changeset_123
Content-Type: application/http
Content-Transfer-Encoding:binary

PATCH PostingBatch(batchId=19,postingBatchId=1) HTTP/1.1
Content-Type: application/json

{
    "batchId": 19,
    "postingBatchId": 1,
    "postingStatus": "SUCCESS",
    "postingStatusMessage": "Document posted successfully: BKPFF 1700000026DE102023 SD1CLNT200 | ",
    "postingDocument": "1700000026"
}
--changeset_123--

--batch_123--